#include "ft_printf.h"

int main()
{
    char *line;

	printf("%s", "\n\n****************************  CONV. NORMALES  ******************************\n\n");
    //printf("MY res %d\n", ft_printf("%d\n", 123));
    //printf("REEL %d\n\n", printf("%d\n", 123));
    //printf("MY res %d\n", ft_printf("%i\n", 321));
    //printf("REEL %d\n", printf("%i\n", 321));
	//printf("MY res %d\n\n", ft_printf("%u\n", 21474836));
	//printf("REEL %d\n", printf("%u\n", 21474836));
	//printf("MY res %d\n\n", ft_printf("%x\n", 1234567890));
	//printf("REEL %d\n", printf("%x\n", 1234567890));
	//printf("MY res %d\n\n", ft_printf("%X\n", 123));
	//printf("REEL %d\n", printf("%X\n", 123));
	printf("MY res %d\n\n", ft_printf("%p\n", &line));
	printf("REEL %d\n", printf("%p\n", &line));
	//printf("MY res %d\n\n", ft_printf("%c\n", 'p'));
	//printf("REEL %d\n", printf("%c\n", 'p'));
	//printf("MY res %d\n\n", ft_printf("%c\n", 0));
	//printf("REEL %d\n", printf("%c\n", 0));
	//printf("MY res %d\n\n", ft_printf("%s\n", "bonjour les copains"));
	//printf("REEL %d\n", printf("%s\n", "bonjour les copains"));
	printf("%s", "\n\n*****************************   FLAGS MOINS  ***************************\n\n");
	printf("MY res %d\n\n", ft_printf("%-180s\n", "coucou"));
	printf("REEL %d\n", printf("%-180s\n", "coucou"));
	printf("MY res %d\n\n", ft_printf(".%-2d.\n", 123));
	printf("REEL %d\n", printf(".%-2d.\n", 123));
	printf("MY res %d\n\n", ft_printf(".%-1c.\n", 'p'));
	printf("REEL %d\n", printf(".%-1c.\n", 'p'));
	printf("MY res %d\n\n", ft_printf(".%-15u.\n", 252525));
	printf("REEL %d\n", printf(".%-15u.\n", 252525));
	printf("MY res %d\n\n", ft_printf(".%-1x.\n", 123));
	printf("REEL %d\n", printf(".%-1x.\n", 123));
	printf("MY res %d\n\n", ft_printf(".%-9X.\n", 123));
	printf("REEL %d\n", printf(".%-9X.\n", 123));
	printf("MY res %d\n\n", ft_printf(".%-2p.\n", &line));
	printf("REEL %d\n", printf(".%-2p.\n", &line));
	printf("%s", "\n\n*****************************   FLAGS POINT ***************************\n\n");
	printf("MY res %d\n", ft_printf(".%.1i.\n", 42));
	printf("REEL %d\n\n", printf(".%.1i.\n", 42));
	printf("MY res %d\n", ft_printf(".%.18u.\n", 234567890));
	printf("REEL %d\n\n", printf(".%.18u.\n", 234567890));
	printf("MY res %d\n", ft_printf(".%.6x.\n", 890));
	printf("REEL %d\n\n", printf(".%.6x.\n", 890));
	printf("MY res %d\n", ft_printf(".%.18X.\n", 890));
	printf("REEL %d\n\n", printf(".%.18X.\n", 890));
	printf("MY res %d\n", ft_printf(".%.4s.\n", "coucou"));
	printf("REEL %d\n\n", printf(".%.4s.\n", "coucou"));
	printf("%s", "\n\n*****************************   FLAGS ZERO ***************************\n\n");
	printf("MY res %d\n", ft_printf(".%04d.\n", 42));
	printf("REEL %d\n\n", printf(".%04d.\n", 42));
	printf("MY res %d\n", ft_printf(".%04i.\n", 42));
	printf("REEL %d\n\n", printf(".%04i.\n", 42));
	printf("MY res %d\n", ft_printf(".%09x.\n", 349));
	printf("REEL %d\n\n", printf(".%09x.\n", 349));
	printf("MY res %d\n", ft_printf(".%09X.\n", 349));
	printf("REEL %d\n\n", printf(".%09X.\n", 349));
	printf("MY res %d\n", ft_printf(".%07u.\n", 42));
	printf("REEL %d\n\n", printf(".%07u.\n", 42));
	printf("MY res %d\n", ft_printf(".%07i.\n", 42));
	printf("REEL %d\n\n", printf(".%07i.\n", 42));
	printf("%s", "\n\n*****************************   FLAGS MIN ***************************\n\n");
	printf("MY res %d\n", ft_printf(".%10s.\n", "coucou"));
	printf("REEL %d\n\n", printf(".%10s.\n", "coucou"));
	printf("MY res %d\n", ft_printf(".%5c.\n", 'c'));
	printf("REEL %d\n\n", printf(".%5c.\n", 'c'));
	printf("MY res %d\n", ft_printf(".%17p.\n", &line));
	printf("REEL %d\n\n", printf(".%17p.\n", &line));
	printf("MY res %d\n", ft_printf(".%5d.\n", 42));
	printf("REEL %d\n\n", printf(".%5d.\n", 42));
	printf("MY res %d\n", ft_printf(".%17x.\n", 42));
	printf("REEL %d\n\n", printf(".%17x.\n", 42));
	printf("MY res %d\n", ft_printf(".%17X.\n", 42));
	printf("REEL %d\n\n", printf(".%17X.\n", 42));
	printf("MY res %d\n", ft_printf(".%6i.\n", 42));
	printf("REEL %d\n\n", printf(".%6i.\n", 42));
	//printf("MY res %d\n", ft_printf(".%.180s.\n", "coucou"));
	//printf("REEL %d\n\n", printf(".%.180s.\n", "coucou"));
    //printf("MY res %d\n", ft_printf("%d\n%i\n%u\n%x\n%X\n%p\n%s\n%c\n", 123, 321, 2147483650, 4569695, 4569695, &line, "bonjour les copains", 'c'));
    //printf("REEL %d\n", printf("%d\n%i\n%ld\n%x\n%X\n%p\n%s\n%c\n", 123, 321, 2147483650, 4569695, 4569695, &line, "bonjour les copains", 'c'));
    return (0);
}